### ISSUE TITLE
Return value from ParserProxy.visit method

### ISSUE THREAD

**Issue by zakjan** [camertron/antlr4-native-rb#1]
Currently, ParserProxy.visit method doesn't return any value.

```
  VALUE visit(VisitorProxy* visitor) {
    visitor -> visit(this -> parser -> syntax());
    ...
    return Qnil;
  }
```

My Ruby visitor returns objects from visit_* methods. How can I propagate them through ParserProxy.visit? I tried to update the method code in various ways and recompile, but haven't succeeded yet. Usually I received `RuntimeError: std::bad_cast` or `ArgumentError: Unable to convert antlrcpp::Any*` in runtime.

**Comment by zakjan** [comment]
Closing, I found a solution and I sent a PR #3 instead.

**Comment by camertron** [comment]
Hey @zakjan thanks for reaching out. Apologies for not responding sooner. Also, thanks for the PRs! I'm looking at them now.
