### ISSUE TITLE
A probable root cause of segfaults (2)

### ISSUE THREAD

**Issue by maxirmx** [camertron/antlr4-native-rb#10]
ParserProxy class has members  that are pointers to parser, tokens, lexer and input Antlr objects
These objects are deleted in ParserProxy destructor

This can cause an issue if Ruby code had obtained a reference to one of these objects and after that ParserProxy is garbage collected.
This is the case described at Rice documentation https://jasonroelofs.com/rice/4.x/advanced/functions.html#keep-alive  -- the second example.

In order to resolve this issue ```Return().keepAlive()``` shall be applied to definition of ParserProxy methods
```
  rb_cParser = define_class_under<ParserProxy>(rb_mExpressParser, "Parser")
    .define_singleton_function("parse", &ParserProxy::parse)
    .define_singleton_function("parse_file", &ParserProxy::parseFile)
    .define_method("syntax", &ParserProxy::syntax, Return().keepAlive())
    .define_method("visit", &ParserProxy::visit, Return().keepAlive());
```

**Comment by camertron** [comment]
Makes sense, thanks @maxirmx :) Closing this in favor of the PR.
