### ISSUE TITLE
NULL as a keyword in the target language breaks compilation

### ISSUE THREAD

**Issue by jacobobq** [camertron/antlr4-native-rb#15]
So... C++, right? Has a macro somewhere called `NULL`. And when tokens are generated in the source code of the parser they use the token itself as name. Now, SQL has a `NULL` keyword so trying to generate a grammar for any flavor of it fails because `NULL` is already defined.

For instance, take the Trino's (formerly PrestoSQL) [grammar definition](https://github.com/trinodb/trino/blob/master/core/trino-parser/src/main/antlr4/io/trino/sql/parser/SqlBase.g4). This will fail to compile the generated `.h/.cpp` files.

**Expected behaviour:**
It compiles normally.

**Comment by jacobobq** [comment]
The approach I'd take is add an `#undef NULL` (and make sure we don't ever use the original `NULL`). Let me know if this is good so we can send a PR.

**Comment by jacobobq** [comment]
I'm trying to find a way to solve this (probably prefix all tokens) and I will try to send you a PR.

Currently no luck.

**Comment by camertron** [comment]
Hey @jacobobq, thanks for bringing this up. Symbol clashes like this are a known class of problem with ANTLR that is unlikely to be addressed. [Here's](https://github.com/antlr/antlr4/issues/2029) a very similar issue to the one you brought up. As suggested, you might try adding an underscore to the end, eg. `NULL_`.
