### ISSUE TITLE
Dasherized output dir is different from ruby dir name conventions

### ISSUE THREAD

**Issue by zakjan** [camertron/antlr4-native-rb#7]
I understand that this library is primarily meant to create a standalone gem with `gemerator`. However, it can be used to generate part of a larger gem as well, where the user can `require` the bundle where needed.

Would you mind changing to `dasherize` to `underscore` in `gem_name` to match ruby dir name conventions, or maybe better remove `gem_name` from `interop_file` and `antlrgen_dir` completely, give the full control to the caller with `output_dir` param?

I stumbled upon this when using [rake-compiler](https://github.com/rake-compiler/rake-compiler), default config assumes that the output bundle name is the same as the ext dir name. This produces a dasherized bundle name.

**Comment by camertron** [comment]
Hey @zakjan. I'm not entirely sure what you mean, but as long as antlr-gemerator and antlr4-native-rb can work together in harmony, I'm probably going to be ok with any changes. Happy to look at a PR :)

**Comment by zakjan** [comment]
I looked into gemerator more in detail and It seems that gemerator is pretty coupled with your existing directory conventions.

The reason why I asked is that currently when using rake-compiler, now I have to override ext_dir from default value:

```
Rake::ExtensionTask.new "express_parser" do |ext|
  ext.ext_dir = "ext/express-parser" # default "ext/express_parser"
end
```

This produces the bundle at `lib/express_parser.bundle` and can be imported with `require "express_parser"`, as if it would be a regular Ruby file.

**Comment by zakjan** [comment]
I'm sorry, I'm going to close this one, currently I don't have capacity to send a PR. We can leave it as a food for thoughts.

**Comment by camertron** [comment]
Hey @zakjan, sorry for taking so long to respond. As I recall, I ran into some weird issue using dashes instead of underscores, but maybe that was caused by something else? If dashes are more of a convention in the native extension world, then I'm fine switching over.

No problem, always happy to look at a PR should you decide to submit one :)
