### ISSUE TITLE
A probable root cause of segfaults (1)

### ISSUE THREAD

**Issue by maxirmx** [camertron/antlr4-native-rb#9]
The method ```ContextProxy::getChildren```  returns Ruby array of Ruby objects:

```
class ContextProxy {
...
  Array getChildren() {
    if (children == nullptr) {
      children = new Array();

      if (orig != nullptr) {
        for (auto it = orig -> children.begin(); it != orig -> children.end(); it ++) {
          Object parseTree = ContextProxy::wrapParseTree(*it);

          if (parseTree != Nil) {
            children -> push(parseTree);
          }
        }
      }
    }

    return *children;
  }
...
}
```
C++ actually crates a copy of ```*children```  that is returned to caller.  Objects in the array are not copied, of course.
When Ruby GarbageCollector frees the array it also unmarks and frees all objects contained in the array.  However, the code above potentially reuses these objects without marking them. It looks like athe root cause for at least some of the crashes discussed  at https://github.com/camertron/antlr4-native-rb#caveats

I have indirect validation of this idea.  In the recent version of https://github.com/lutaml/expressir we had reproducible segfaults.  Resolving the issue that I have described  also resolved segfaults.

**Comment by maxirmx** [comment]
There are two possible solutions

- Create array on each call to getChildren (which I tried)

```
  Array getChildren() {
    Array children;
    if (orig != nullptr) {
      for (auto it = orig -> children.begin(); it != orig -> children.end(); it ++) {
        Object parseTree = ContextProxy::wrapParseTree(*it);
        if (parseTree != Nil) {
          children.push(parseTree);
        }
      }
    }
    return children;
  }
```
- Implement custom mark function. There is some clue here https://jasonroelofs.com/rice/4.x/advanced/memory_management.html#ruby-to-c

**Comment by camertron** [comment]
Wow, Rice v4 really added some awesome features. Thank you for figuring this out :) Closing in favor of the PR.
